" DG's vim config file, Hell Yeah Brother!
" General configs
colorscheme desert
set tabstop=4
set shiftwidth=4
set softtabstop=4
set colorcolumn=110
set encoding=utf-8
set autoindent
set mouse=a
set hidden
set nowrap
set exrc
set secure
set nohlsearch 
set number
set belloff=all
set completeopt-=preview
highlight LineNr ctermfg=darkgray
syntax enable
filetype on

" neovim additions
set clipboard=unnamedplus

" ex sudo in vim 
cmap w!! w !sudo tee > /dev/null %

" Ask to make directory if does not exist
augroup vimrc-auto-mkdir
    autocmd!
    autocmd BufWritePre * call s:auto_mkdir(expand('<afile>:p:h'), v:cmdbang)
    function! s:auto_mkdir(dir, force)
        if !isdirectory(a:dir)
            \ && (a:force
            \ || input("'" . a:dir . "' does not exist. Create? [y/n]") =~? '^y\%[es]$')

            call mkdir(iconv(a:dir, &encoding, &termencoding), 'p')
        endif
    endfunction
augroup END

" Plugins
call plug#begin()
Plug 'valloric/YouCompleteMe'
Plug 'tmsvg/pear-tree'
Plug 'dense-analysis/ale'
Plug 'sheerun/vim-polyglot'
Plug 'francoiscabrol/ranger.vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
call plug#end()

" Visual block
noremap X <c-v>

nnoremap ; :

" save file
map <C-s> :w<CR>

" exit
map <C-q> :q<CR>

" cycle buffers
:nnoremap <Tab> :bnext<CR>

" move around splits
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h

" Tree explorer
let g:ranger_map_keys = 0
map <C-n> :Ranger<CR> 

let g:airline_theme='solarized'
let g:airline#extensions#tabline#enabled = 2
let g:airline#extensions#tabline#formatter = 'unique_tail'
let g:airline_section_y = ""
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline#extensions#tabline#right_sep = ' '
let g:airline#extensions#tabline#right_alt_sep = '|'
let g:airline_left_sep = ' '
let g:airline_left_alt_sep = '|'
let g:airline_right_sep = ' '
let g:airline_right_alt_sep = '|'

" Word Processor mode
func! WordProcessorMode()
	setlocal textwidth=80
	setlocal smartindent
	setlocal spell spelllang=en_us
	setlocal noexpandtab
endfu
com! WP call WordProcessorMode()

" Python formatting
au BufNewFile,BufRead *.py
    \ set textwidth=79 |
    \ set autoindent

au BufNewFile,BufRead *.{js,json}
    \ set softtabstop=2 |
    \ set expandtab |
    \ set shiftwidth=2 |
    \ set tabstop=2

" C/C++ configs
nnoremap <F4> :make!<cr>

let g:ale_linters = {
        \   'python': ['pylint'],
        \   'javascript': ['eslint'],
        \}
