" DG's vim config file, Hell Yeah Brother!
" General configs
colorscheme desert
set tabstop=4
set shiftwidth=4
set softtabstop=4
set colorcolumn=110
set encoding=utf-8
set expandtab
set autoindent
set mouse=a
set hidden
set nowrap
set exrc
set secure
syntax on 
filetype on
set nohlsearch 
set number
set belloff=all
set completeopt-=preview
highlight LineNr ctermfg=darkgray

" ex sudo in vim 
cmap w!! w !sudo tee > /dev/null %

" Ask to make directory if does not exist
augroup vimrc-auto-mkdir
    autocmd!
    autocmd BufWritePre * call s:auto_mkdir(expand('<afile>:p:h'), v:cmdbang)
    function! s:auto_mkdir(dir, force)
        if !isdirectory(a:dir)
            \ && (a:force
            \ || input("'" . a:dir . "' does not exist. Create? [y/n]") =~? '^y\%[es]$')

            call mkdir(iconv(a:dir, &encoding, &termencoding), 'p')
        endif
    endfunction
augroup END

" Plugins
call plug#begin()
Plug 'preservim/NERDTree'
Plug 'valloric/YouCompleteMe'
Plug 'tmsvg/pear-tree'
Plug 'dense-analysis/ale'
Plug 'sheerun/vim-polyglot'
call plug#end()

" Visual block
noremap X <c-v>

" save file
map <C-s> :w<CR>

" exit
map <C-q> :q<CR>

" move around splits
map <c-j> <c-w>j
map <c-k> <c-w>k
map <c-l> <c-w>l
map <c-h> <c-w>h

" NERDTree
map <C-n> :NERDTreeToggle<CR> | :let NERDTreeWinSize = 15 | :wincmd w

" Word Processor mode
func! WordProcessorMode()
	setlocal textwidth=80
	setlocal smartindent
	setlocal spell spelllang=en_us
	setlocal noexpandtab
endfu
com! WP call WordProcessorMode()

" Python formatting
au BufNewFile,BufRead *.py
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set autoindent |
    \ set fileformat=unix``

au BufNewFile,BufRead *.js
    \ set softtabstop=2 |
    \ set shiftwidth=2 |
    \ set tabstop=2

au BufNewFile,BufRead *.json
    \ set softtabstop=2 |
    \ set shiftwidth=2 |
    \ set tabstop=2

" C/C++ configs
nnoremap <F4> :make!<cr>

let g:ale_linters = {
        \   'python': ['pylint'],
        \   'javascript': ['eslint'],
        \}
