" DG's vim config file, Hell Yeah Brother!
" General configs
colorscheme desert 
set tabstop=4
set shiftwidth=4
set softtabstop=4
set colorcolumn=110
set encoding=utf-8
set expandtab
set autoindent
set mouse=a
set hidden
set nowrap
set exrc
set secure
set nohlsearch 
syntax on
set number
set belloff=all
highlight LineNr ctermfg=darkgray

" ex sudo in vim 
cmap w!! w !sudo tee > /dev/null %

" Ask to make directory if does not exist
augroup vimrc-auto-mkdir
    autocmd!
    autocmd BufWritePre * call s:auto_mkdir(expand('<afile>:p:h'), v:cmdbang)
    function! s:auto_mkdir(dir, force)
        if !isdirectory(a:dir)
            \ && (a:force
            \ || input("'" . a:dir . "' does not exist. Create? [y/N]") =~? '^y\%[es]$')

            call mkdir(iconv(a:dir, &encoding, &termencoding), 'p')
        endif
    endfunction
augroup END

" Plugins
call plug#begin()
Plug 'preservim/NERDTree'
" Plug 'arcticicestudio/nord-vim'
Plug 'valloric/YouCompleteMe'
Plug 'tmsvg/pear-tree'
Plug 'dense-analysis/ale'
call plug#end()

" Visual block
noremap X <c-v>

" save file
map <C-s> :w<CR>

" save and exit
" map <C-x> :x<CR>

" exit
map <C-q> :q<CR>

" copy
xnoremap <silent> <C-C> :w !wl-copy<CR><CR>

" NERDTree
map <C-n> :NERDTreeToggle<CR> | :let NERDTreeWinSize = 15 | :wincmd w

" Word Processor mode
func! WordProcessorMode()
	setlocal textwidth=80
	setlocal smartindent
	setlocal spell spelllang=en_us
	setlocal noexpandtab
endfu
com! WP call WordProcessorMode()

au BufNewFile,BufRead *.js
    \ set softtabstop=2 |
    \ set shiftwidth=2 |
    \ set tabstop=2

au BufNewFile,BufRead *.json
    \ set softtabstop=2 |
    \ set shiftwidth=2 |
    \ set tabstop=2

" Python formatting
au BufNewFile,BufRead *.py
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix``

" C/C++ configs
nnoremap <F4> :make!<cr>
