swipe:
  3:
    right:
      command: 'swaymsg "workspace next"'
    left:
      command: 'swaymsg "workspace prev"'
  4:
    up:
      command: 'swaymsg "move scratchpad"'
    down:
      command: 'swaymsg "scratchpad show"'
    right:
      command: 'swaymsg "workspace next"'
    left:
      command: 'swaymsg "workspace prev"'
